env:
  TERM: alacritty

import:
  - ~/.config/alacritty/colors/kanagawa.yaml

window:
  dimensions:
    columns: 120
    lines: 35
  decorations: full
  padding:
    x: 10
    y: 10
  title: 'Terminal'
  dynamic_title: false
  opacity: 1
  startup_mode: 'Fullscreen'

scrolling:
  history: 5000

font:
  # Normal Mode
  size: 20.0
  # Presentation Mode
  # size: 26.0
  normal:
    family: 'GoMono Nerd Font Mono'
    style: 'Book'
  bold:
    family: 'GoMono Nerd Font Mono'
    style: 'Bold'
  italic:
    family: 'GoMono Nerd Font Mono'
    style: 'Italic'
  bold_italic:
    family: 'GoMono Nerd Font Mono'
    style: 'Bold Italic'
  use_thin_strokes: true

selection:
  save_to_clipboard: true
