env:
  TERM: alacritty

import:
- ~/.config/alacritty/colors/github_light.yaml

window:
  dimensions:
    columns: 120
    lines: 35
  decorations: full
  padding:
    x: 10
    y: 10
  title: 'Terminal'
  dynamic_title: false
  opacity: 1

scrolling:
  history: 5000

font:
  # Normal Mode
  size: 18.0
  # Presentation Mode
  # size: 32.0
  normal:
    family: 'FiraCode Nerd Font'
    style: 'Retina'
  bold:
    family: 'FiraCode Nerd Font'
    style: 'Bold'
  italic:
    family: 'Fira Code'
    style: 'Italic'
  bold_italic:
    family: 'Fira Code'
    style: 'Bold Italic'
  use_thin_strokes: true

selection:
  save_to_clipboard: true

